### ISSUE TITLE
Remove successful logged notifications when WLAN's off

### ISSUE THREAD

**Issue by phy25** [entalent/BIT_NetCheckin2#17]
Remove "login successful" notification when WLAN is off (changed to mobile network or some other WiFi) to prevent confusion. It's good if this is implemented.

**Comment by LangleyChang** [comment]
Not complicated I guess.I'll take it into consideration.

**Comment by LangleyChang** [comment]
Fixed in [#19](https://github.com/entalent/BIT_NetCheckin2/pull/19)
